### ISSUE TITLE
A new operation directly after equals does not work correctly

### ISSUE THREAD

**Issue by massimocode** [SMH110/My-Calculator#7]
Replication steps:
Press the following buttons strictly in this order
1) 123 + 3 = (displays 126, which is correct)
2) 321 + 1 = (displays 126322, I expect 322!)

This does not match common calculator behaviour.

**Comment by SMH110** [comment]
This bug has been fixed in 1c6e5afbf2aa3122186156758ea1d3088941790f

**Comment by massimocode** [comment]
I have got the latest code and retried it and I can still replicate the bug. I looked at the commit you mentioned and it doesn't seem to fix the bug. Did you forget to stage your changes or something?

**Comment by SMH110** [comment]
I have just download the calculator file on my PC and it works fine 
321 +1 = 322 
123 + 3 = 126

**Comment by SMH110** [comment]
see here b6362b68a7fca5287f28ba99ea32385f3ab6ee4a

before it was `if (result === 0)`
now it is:
`if (result === "0")`

**Comment by massimocode** [comment]
That's very strange because I just got the latest code and tried the replication steps exactly and the bug is still there.

You must perform both calculations back to back. i.e. press the following buttons
1, 2, 3, +, 3, =, 3, 2, 1, +, 1, =

**Comment by SMH110** [comment]
Sorry you are right.
before I was pressing Clear before I start the new operation

**Comment by SMH110** [comment]
Now it has been fixed in 222d4d9eec48240e60f2fe9bf912e83a80ae4da5

**Comment by massimocode** [comment]
I have verified this and it's fixed
